//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartBillboard100
    {
        public string ChartID { get; set; }
        public System.DateTime Date { get; set; }
        public string TrackID { get; set; }
        public int Position { get; set; }
        public Nullable<int> PositionAdj { get; set; }
    
        public virtual Track Track { get; set; }
    }
}
