//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSaver.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficialChartsEntities : DbContext
    {
        public OfficialChartsEntities()
            : base("name=OfficialChartsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Chart> Charts { get; set; }
        public virtual DbSet<ChartBillboard100> ChartBillboard100 { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<OnDisc> OnDiscs { get; set; }
        public virtual DbSet<Record_Spotify> Record_Spotify { get; set; }
    }
}
