//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnDisc
    {
        public int ID { get; set; }
        public string OCID { get; set; }
        public Nullable<int> MMID { get; set; }
        public string Artist { get; set; }
        public string SongTitle { get; set; }
        public string Album { get; set; }
        public string SongPath { get; set; }
        public string Extension { get; set; }
        public Nullable<int> SongLength { get; set; }
        public Nullable<int> BitRate { get; set; }
    
        public virtual Track Track { get; set; }
    }
}
